apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: myapp
data:
  PORT: "3000"
  REDIS_HOST: "redis-cluster-headless.redis.svc.cluster.local"  # Replace with Redis service name if different
  REDIS_PORT: "6379"
  PG_HOST: "postgresql-ha-postgresql.postgres.svc.cluster.local"  # Replace with your PostgreSQL service name
  PG_PORT: "5432"
  PG_DATABASE: "your-database"
  PG_USER: "your-pg-user"