apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: vanshpatel/express-app:latest # Replace with your actual Docker image
        ports:
        - containerPort: 3000
        env:
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_HOST
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_PORT
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DATABASE
        - name: PG_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  namespace: myapp
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP




bo85qu6Xu6

