apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-app-ingress
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: express-app.example.com  # Change this to your domain or use a local test domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express-app-service
            port:
              number: 80
