apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-redis-app
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-redis
  template:
    metadata:
      labels:
        app: express-redis
    spec:
      containers:
      - name: express-redis
        image: vanshpatel/express-app
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"  # Redis master service name
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "ABCD"  # Redis password
