apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    role: slave
